# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_PRODUCTBUILD "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_BUILD_SOURCE_DIRS "/home/misha/untitled2;/home/misha/untitled2/_build")
SET(CPACK_CMAKE_GENERATOR "Ninja")
SET(CPACK_COMPONENTS_ALL "main;dev;static;doc")
SET(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
SET(CPACK_COMPONENTS_GROUPING "IGNORE")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_DEBIAN_DEV_FILE_NAME "libuntitled2-dev_0.3.0_amd64.deb")
SET(CPACK_DEBIAN_DEV_PACKAGE_NAME "libuntitled2-dev")
SET(CPACK_DEBIAN_DOC_FILE_NAME "untitled2-doc_0.3.0_amd64.deb")
SET(CPACK_DEBIAN_DOC_PACKAGE_NAME "untitled2-doc")
SET(CPACK_DEBIAN_MAIN_FILE_NAME "untitled2_0.3.0_amd64.deb")
SET(CPACK_DEBIAN_MAIN_PACKAGE_NAME "untitled2")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
SET(CPACK_DEBIAN_PACKAGE_SECTION "misc")
SET(CPACK_DEBIAN_STATIC_FILE_NAME "libuntitled2-static-dev_0.3.0_amd64.deb")
SET(CPACK_DEBIAN_STATIC_PACKAGE_DEPENDS "libuntitled2-dev")
SET(CPACK_DEBIAN_STATIC_PACKAGE_NAME "libuntitled2-static-dev")
SET(CPACK_DEB_COMPONENT_INSTALL "ON")
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_IGNORE_FILES ";/home/misha/untitled2/_build;^/home/misha/untitled2/.?build.?/;^/home/misha/untitled2/.?output.?/;^/home/misha/untitled2/files/var;^/home/misha/untitled2/files/log;CMakeLists.txt.user.*;.*.autosave;.*.status;~$;\\.swp$;\\.git;/\\.git/;/\\.gitlab-ci/;\\.clang-tidy$;\\.cmake-format$;\\.gitignore$;\\.gitattributes$;\\.gitmodules$;\\.gitlab-ci.yml$")
SET(CPACK_INSTALLED_DIRECTORIES "/home/misha/untitled2;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/usr/lib/x86_64-linux-gnu/cmake/MyxCMake/modules;/usr/lib/x86_64-linux-gnu/cmake/MyxCMake/find;/usr/lib/x86_64-linux-gnu/cmake/MyxCMake/sanitizers;/usr/lib/x86_64-linux-gnu/cmake/MyxCMake/thirdparty;/usr/lib/x86_64-linux-gnu/cmake/MyxCMake/functions")
SET(CPACK_NSIS_DISPLAY_NAME "untitled2 0.3.0")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "untitled2 0.3.0")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/misha/untitled2/_build/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "John Doe <mail@johndoe.com>")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.7/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Пример проекта: графическая программа Qt5")
SET(CPACK_PACKAGE_FILE_NAME "untitled2-0.3.0")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "untitled2 0.3.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "untitled2 0.3.0")
SET(CPACK_PACKAGE_NAME "untitled2")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "org.")
SET(CPACK_PACKAGE_VERSION "0.3.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_PROJECT_CONFIG_FILE "/usr/lib/x86_64-linux-gnu/cmake/MyxCMake/modules/MyxCMakeCPackProject.cmake")
SET(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.7/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.7/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.7/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_PACKAGE_SOURCES "ON")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_IGNORE_FILES ";/home/misha/untitled2/_build;^/home/misha/untitled2/.?build.?/;^/home/misha/untitled2/.?output.?/;^/home/misha/untitled2/files/var;^/home/misha/untitled2/files/log;CMakeLists.txt.user.*;.*.autosave;.*.status;~$;\\.swp$;\\.git;/\\.git/;/\\.gitlab-ci/;\\.clang-tidy$;\\.cmake-format$;\\.gitignore$;\\.gitattributes$;\\.gitmodules$;\\.gitlab-ci.yml$")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/misha/untitled2;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/misha/untitled2/_build/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "untitled2-0.3.0")
SET(CPACK_SOURCE_RPM "")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TARGET_ARCH "amd64")
SET(CPACK_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/misha/untitled2/_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
